// ============================================
// CRUCIGRAMA FUTBOLERO - Banco de Preguntas
// Datos verificados de equipos Liga BetPlay
// ============================================

export interface TeamCrosswordData {
  id: string
  name: string
  color: string
  city: string
  words: CrosswordWordEntry[]
}

export interface CrosswordWordEntry {
  word: string      // UPPERCASE, no spaces - the answer
  clue: string      // The question/clue
  category: string  // Category for grouping
}

// ============================================
// LIGA BETPLAY GENERAL - Crucigrama Especial
// ============================================
export const LIGA_BETPLAY_GENERAL: CrosswordWordEntry[] = [
  { word: 'BETPLAY', clue: 'Patrocinador principal de la liga colombiana', category: 'liga' },
  { word: 'DIMAYOR', clue: 'Organización que administra el fútbol profesional colombiano', category: 'liga' },
  { word: 'CONMEBOL', clue: 'Confederación sudamericana de fútbol', category: 'internacional' },
  { word: 'LIBERTADORES', clue: 'Torneo continental más importante de Sudamérica', category: 'torneo' },
  { word: 'SUDAMERICANA', clue: 'Torneo continental equivalente a la Europa League', category: 'torneo' },
  { word: 'COLOMBIA', clue: 'País donde se juega la Liga BetPlay', category: 'geografia' },
  { word: 'BOGOTA', clue: 'Capital de Colombia, sede de Millonarios y Santa Fe', category: 'geografia' },
  { word: 'MEDELLIN', clue: 'Ciudad de los dos equipos más antiguos de Antioquia', category: 'geografia' },
  { word: 'CALI', clue: 'Ciudad sede del clásico vallecaucano', category: 'geografia' },
  { word: 'BARRANQUILLA', clue: 'Ciudad del equipo tiburón', category: 'geografia' },
  { word: 'MANIZALES', clue: 'Ciudad del Once Caldas, capital caldense', category: 'geografia' },
  { word: 'IBAGUE', clue: 'Ciudad del Deportes Tolima, capital del Tolima', category: 'geografia' },
  { word: 'COPA', clue: 'Trofeo que se otorga al campeón', category: 'torneo' },
  { word: 'ASCENSO', clue: 'Categoría de la segunda división del fútbol colombiano', category: 'liga' },
  { word: 'DESCENSO', clue: 'Castigo de bajar a la segunda división', category: 'liga' },
  { word: 'ARBITRO', clue: 'Juez del partido de fútbol', category: 'reglas' },
  { word: 'GOL', clue: 'Tanto anotado en el partido', category: 'reglas' },
  { word: 'PENAL', clue: 'Infracción dentro del área que genera tiro libre directo', category: 'reglas' },
  { word: 'TITULO', clue: 'Campeonato ganado por un equipo', category: 'torneo' },
  { word: 'CLASICO', clue: 'Partido entre los rivales históricos de una ciudad', category: 'futbol' },
  { word: 'SELECCION', clue: 'Equipo nacional de fútbol de Colombia', category: 'futbol' },
  { word: 'CAFETEROS', clue: 'Apodo de la selección Colombia', category: 'futbol' },
  { word: 'JAMES', clue: 'Nombre del mediocampista colombiano más famoso mundialmente', category: 'jugador' },
  { word: 'FALCAO', clue: 'Apellido del Tigre, goleador histórico de la selección', category: 'jugador' },
  { word: 'YERRY', clue: 'Nombre del defensa colombiano que jugó en el Barcelona', category: 'jugador' },
  { word: 'QUINTERO', clue: 'Apellido de Juan Fernando, mediocampista con gol histórico en Mundial 2018', category: 'jugador' },
  { word: 'LUISDIAZ', clue: 'Apellido del extremo colombiano del Liverpool', category: 'jugador' },
  { word: 'OVEJERO', clue: 'Apodo del árbitro Óscar Julián Ruiz', category: 'futbol' },
  { word: 'PEREIRA', clue: 'Ciudad capital de Risaralda con equipo en la liga', category: 'geografia' },
  { word: 'PASTO', clue: 'Ciudad nariñense con equipo en la liga', category: 'geografia' },
  { word: 'BUCARAMANGA', clue: 'Ciudad capital santandereana con equipo en la liga', category: 'geografia' },
  { word: 'MONTERIA', clue: 'Ciudad capital de Córdoba, sede de Jaguares', category: 'geografia' },
  { word: 'VALLEDUPAR', clue: 'Ciudad capital del Cesar, sede de Alianza', category: 'geografia' },
  { word: 'TUNJA', clue: 'Ciudad capital de Boyacá, sede de Chicó', category: 'geografia' },
  { word: 'CANCHA', clue: 'Terreno de juego del fútbol', category: 'futbol' },
  { word: 'BALON', clue: 'Esfera con la que se juega al fútbol', category: 'futbol' },
  { word: 'ESCUADRA', clue: 'Conjunto de jugadores de un equipo', category: 'futbol' },
  { word: 'DELANTERO', clue: 'Jugador cuya posición es la de atacar al arco', category: 'futbol' },
  { word: 'PORTERO', clue: 'Jugador que defiende la portería', category: 'futbol' },
  { word: 'TECNICO', clue: 'Director técnico o entrenador del equipo', category: 'futbol' },
]

// ============================================
// EQUIPOS DE LA LIGA BETPLAY
// ============================================
export const TEAM_CROSSWORD_DATA: TeamCrosswordData[] = [
  {
    id: 'atletico-nacional',
    name: 'Atlético Nacional',
    color: '#00953b',
    city: 'Medellín',
    words: [
      { word: 'NACIONAL', clue: 'Nombre completo del equipo verde de Medellín', category: 'identidad' },
      { word: 'VERDE', clue: 'Color característico del Atlético Nacional', category: 'identidad' },
      { word: 'MEDELLIN', clue: 'Ciudad donde fue fundado el Atlético Nacional', category: 'geografia' },
      { word: 'ATANASIO', clue: 'Nombre del estadio donde juega Nacional: Estadio ___ Girardot', category: 'estadio' },
      { word: 'REYDECOPAS', clue: 'Apodo histórico del Atlético Nacional por sus títulos internacionales', category: 'apodo' },
      { word: 'LIBERTADORES', clue: 'Torneo continental que Nacional ganó en 1989 y 2016', category: 'torneo' },
      { word: 'ESCobar', clue: 'Apellido de Andrés, el defensa trágicamente asesinado en 1994', category: 'jugador' },
      { word: 'ONCE', clue: 'Número de títulos de liga que tiene Nacional (hasta 2024)', category: 'historia' },
      { word: 'ALVAREZ', clue: 'Apellido de Juan Pablo, mediocampista histórico verde', category: 'jugador' },
      { word: 'ARISTIZABAL', clue: 'Apellido de Víctor Hugo, goleador histórico del equipo verde', category: 'jugador' },
      { word: 'PABLO', clue: 'Nombre de Juan Pablo, ídolo verde de los años 80', category: 'jugador' },
      { word: 'ANTIOQUIA', clue: 'Departamento donde está radicado el equipo', category: 'geografia' },
      { word: 'MILNOVECIENTOS', clue: 'Siglo en que fue fundado Nacional (1947)', category: 'historia' },
      { word: 'PURACE', clue: 'Nombre de la tribuna popular del Atanasio Girardot', category: 'estadio' },
      { word: 'SUR', clue: 'Tribuna donde se ubica la barra Sur del Atlético Nacional', category: 'estadio' },
      { word: 'COPA', clue: 'Torneo que Nacional ha ganado múltiples veces', category: 'torneo' },
      { word: 'RENE', clue: 'Nombre de Higuita, el arquero escorpionero', category: 'jugador' },
      { word: 'HIGUITA', clue: 'Apellido del arquero famoso por la parada del escorpión', category: 'jugador' },
      { word: 'PANAMERICANA', clue: 'Torneo continental de clubes que Nacional ganó en dos ocasiones', category: 'torneo' },
      { word: 'CARDONA', clue: 'Apellido de un talentoso mediocampista verde de los 2010s', category: 'jugador' },
      { word: 'IBARRA', clue: 'Apellido de un lateral derecho histórico del equipo', category: 'jugador' },
      { word: 'ZUNIGA', clue: 'Apellido de Juan Camilo, lateral que jugó en Nacional', category: 'jugador' },
      { word: 'GIOVANNI', clue: 'Nombre de Moreno, delantero colombiano que brilló en Nacional', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de Giovanni, mediapunta ídolo del verde', category: 'jugador' },
      { word: 'DORLAN', clue: 'Nombre de Pabón, delantero goleador de Nacional', category: 'jugador' },
      { word: 'PABON', clue: 'Apellido de Dorlan, goleador que jugó en Nacional', category: 'jugador' },
      { word: 'JARLAN', clue: 'Nombre del mediocampista Barrera, canterano verde', category: 'jugador' },
      { word: 'BARRERA', clue: 'Apellido de Jarlan, volante canterano del verde', category: 'jugador' },
      { word: 'LUIS', clue: 'Nombre de Díaz, extremo que pasó por Nacional antes de ir a Europa', category: 'jugador' },
      { word: 'DIAZ', clue: 'Apellido de Luis, extremo que jugó en Nacional antes del Porto', category: 'jugador' },
      { word: 'VERDOLAGA', clue: 'Apodo alternativo del Atlético Nacional', category: 'apodo' },
      { word: 'MATADOR', clue: 'Apodo del goleador arrollador del verde', category: 'apodo' },
      { word: 'BOLILLO', clue: 'Apodo del técnico Hernán Gómez, campeón con Nacional', category: 'tecnico' },
      { word: 'BURIAN', clue: 'Apellido de un técnico uruguayo campeón con Nacional', category: 'tecnico' },
      { word: 'AUTUORI', clue: 'Apellido de Paulo, técnico brasileño campeón de Libertadores con Nacional', category: 'tecnico' },
      { word: 'REPECHAJE', clue: 'Ronda previa a la fase de grupos de Copa Libertadores', category: 'torneo' },
    ]
  },
  {
    id: 'millonarios',
    name: 'Millonarios',
    color: '#0033a0',
    city: 'Bogotá',
    words: [
      { word: 'MILLONARIOS', clue: 'Nombre del equipo azul de Bogotá', category: 'identidad' },
      { word: 'AZUL', clue: 'Color característico de Millonarios', category: 'identidad' },
      { word: 'BOGOTA', clue: 'Ciudad donde fue fundado Millonarios en 1946', category: 'geografia' },
      { word: 'NEMESIO', clue: 'Nombre del estadio Camilo ___ donde juega Millonarios', category: 'estadio' },
      { word: 'CAMILO', clue: 'Segundo nombre del estadio ___ Camacho donde juega Millos', category: 'estadio' },
      { word: 'EMBAJADOR', clue: 'Apodo de Millonarios por sus giras internacionales', category: 'apodo' },
      { word: 'DIABLO', clue: 'Parte del apodo del equipo: Los ___ Azules', category: 'apodo' },
      { word: 'ALFREDO', clue: 'Nombre de Di Stéfano, jugador legendario de Millonarios', category: 'jugador' },
      { word: 'DISTEFANO', clue: 'Apellido de Alfredo, el jugador más famoso que pasó por Millos', category: 'jugador' },
      { word: 'PEDRO', clue: 'Nombre de Zape, delantero histórico de Millonarios', category: 'jugador' },
      { word: 'ZAPE', clue: 'Apellido de Pedro, goleador histórico azul', category: 'jugador' },
      { word: 'CUNDINAMARCA', clue: 'Departamento donde está radicado Millonarios', category: 'geografia' },
      { word: 'QUINCE', clue: 'Número de títulos de liga que tiene Millonarios (hasta 2024)', category: 'historia' },
      { word: 'ROJAS', clue: 'Apellido de un mediocampista emblemático azul', category: 'jugador' },
      { word: 'WILSON', clue: 'Nombre de Morelos, delantero goleador de Millos', category: 'jugador' },
      { word: 'MORELOS', clue: 'Apellido de Wilson, goleador colombiano de Millonarios', category: 'jugador' },
      { word: 'CABAL', clue: 'Apellido de un volante histórico de Millonarios', category: 'jugador' },
      { word: 'GOLFIN', clue: 'Apellido de un mediocampista azul de los años 80', category: 'jugador' },
      { word: 'SANTA', clue: 'Primera parte del rival clásico: ___ Fe', category: 'clasico' },
      { word: 'CLASICO', clue: 'Partido entre Millonarios y Santa Fe', category: 'clasico' },
      { word: 'CAPITALINO', clue: 'Adjetivo del clásico bogotano entre Millos y Santa Fe', category: 'clasico' },
      { word: 'PATRON', clue: 'Apodo reciente de los hinchas de Millonarios', category: 'apodo' },
      { word: 'ORO', clue: 'Color que acompaña al azul en la bandera de Millonarios', category: 'identidad' },
      { word: 'DORADO', clue: 'Período histórico de Millonarios en los años 50', category: 'historia' },
      { word: 'BLUE', clue: 'Palabra en inglés que identifica la hinchada de Millos', category: 'apodo' },
      { word: 'COMANDO', clue: 'Nombre de la barra brava de Millonarios', category: 'hinchada' },
      { word: 'REY', clue: 'Apodo que se da a Millonarios por su historia gloriosa', category: 'apodo' },
      { word: 'LIBERTADORES', clue: 'Torneo continental donde Millonarios fue semifinalista', category: 'torneo' },
      { word: 'GAMARRA', clue: 'Apellido de un volante azul de los años 2000', category: 'jugador' },
      { word: 'GERMAN', clue: 'Nombre de Efrain, arquero cantero azul de los 2010s', category: 'jugador' },
      { word: 'ACOSTA', clue: 'Apellido de un volante creativo de Millonarios', category: 'jugador' },
      { word: 'TERMINADO', clue: 'Apodo de la barra de Millos: Los ___ Blue Rain', category: 'hinchada' },
      { word: 'LENGUAR', clue: 'Apellido de un histórico arquero de Millonarios', category: 'jugador' },
      { word: 'DELGADO', clue: 'Apellido de un delantero histórico azul', category: 'jugador' },
    ]
  },
  {
    id: 'america-de-cali',
    name: 'América de Cali',
    color: '#e31937',
    city: 'Cali',
    words: [
      { word: 'AMERICA', clue: 'Nombre del equipo rojo de Cali', category: 'identidad' },
      { word: 'ROJO', clue: 'Color característico del América de Cali', category: 'identidad' },
      { word: 'CALI', clue: 'Ciudad donde fue fundado el América en 1927', category: 'geografia' },
      { word: 'PASCUAL', clue: 'Nombre del estadio donde juega América: Estadio ___ Guerrero', category: 'estadio' },
      { word: 'GUERRERO', clue: 'Apellido que completa el nombre del estadio de América', category: 'estadio' },
      { word: 'DIABLO', clue: 'Apodo del América: Los ___ Rojos', category: 'apodo' },
      { word: 'MECHITA', clue: 'Apodo cariñoso del América de Cali', category: 'apodo' },
      { word: 'VALLE', clue: 'Departamento donde está radicado el América', category: 'geografia' },
      { word: 'CAUCA', clue: 'Río que pasa por la ciudad del América de Cali', category: 'geografia' },
      { word: 'LIBERTADORES', clue: 'Torneo donde América fue subcampeón cuatro veces', category: 'torneo' },
      { word: 'CUATRO', clue: 'Número de veces que América fue subcampeón de Libertadores', category: 'torneo' },
      { word: 'QUINCE', clue: 'Número de títulos de liga del América (hasta 2024)', category: 'historia' },
      { word: 'RINCON', clue: 'Apellido de Anthony, delantero goleador de América', category: 'jugador' },
      { word: 'DUVAN', clue: 'Nombre de Zapata, delantero que pasó por América', category: 'jugador' },
      { word: 'ZAPATA', clue: 'Apellido de Duvan, delantero que surgió en América', category: 'jugador' },
      { word: 'ADRIAN', clue: 'Nombre de Ramos, mediocampista histórico del América', category: 'jugador' },
      { word: 'RAMOS', clue: 'Apellido de Adrián, volante histórico escarlata', category: 'jugador' },
      { word: 'GAVIRIA', clue: 'Apellido de un volante histórico del América', category: 'jugador' },
      { word: 'CLASICO', clue: 'Partido entre América y Deportivo Cali', category: 'clasico' },
      { word: 'VALLECAUCANO', clue: 'Adjetivo del clásico entre América y Deportivo Cali', category: 'clasico' },
      { word: 'ESCANDALO', clue: 'Término asociado a la era de los años 80 del América', category: 'historia' },
      { word: 'VERDE', clue: 'Color del rival de barrio del América', category: 'clasico' },
      { word: 'SARDI', clue: 'Apellido de un volante histórico escarlata', category: 'jugador' },
      { word: 'MIGUEL', clue: 'Nombre de Calero, arquero escarlata histórico', category: 'jugador' },
      { word: 'CALERO', clue: 'Apellido de Miguel, arquero que jugó en América', category: 'jugador' },
      { word: 'PABLO', clue: 'Nombre de Armero, lateral que pasó por América', category: 'jugador' },
      { word: 'ARMERO', clue: 'Apellido de Pablo, lateral escarlata', category: 'jugador' },
      { word: 'HERRERA', clue: 'Apellido de un delantero histórico del América', category: 'jugador' },
      { word: 'BARRIOS', clue: 'Apellido de un mediocampista escarlata', category: 'jugador' },
      { word: 'CORDOBA', clue: 'Apellido de un defensa histórico del América', category: 'jugador' },
      { word: 'SIERRA', clue: 'Apellido de un volante creativo del América', category: 'jugador' },
      { word: 'OLIVARES', clue: 'Apellido de un delantero goleador escarlata', category: 'jugador' },
    ]
  },
  {
    id: 'deportivo-cali',
    name: 'Deportivo Cali',
    color: '#007a33',
    city: 'Cali',
    words: [
      { word: 'CALI', clue: 'Nombre del equipo verde de Cali', category: 'identidad' },
      { word: 'VERDE', clue: 'Color característico del Deportivo Cali', category: 'identidad' },
      { word: 'DEPORTIVO', clue: 'Primera parte del nombre completo del equipo', category: 'identidad' },
      { word: 'PALMASECA', clue: 'Nombre del estadio del Deportivo Cali', category: 'estadio' },
      { word: 'AZUCARERO', clue: 'Apodo del Deportivo Cali por la industria azucarera del Valle', category: 'apodo' },
      { word: 'VALLE', clue: 'Departamento donde está radicado el Deportivo Cali', category: 'geografia' },
      { word: 'COPA', clue: 'Torneo que Cali ganó en 2021 por primera vez en años', category: 'torneo' },
      { word: 'NUEVE', clue: 'Número de títulos de liga del Deportivo Cali', category: 'historia' },
      { word: 'TEOFILO', clue: 'Nombre de Gutiérrez, delantero histórico del Cali', category: 'jugador' },
      { word: 'GUTIERREZ', clue: 'Apellido de Teófilo, goleador histórico verdiblanco', category: 'jugador' },
      { word: 'MARIANO', clue: 'Nombre de un mediocampista histórico del Cali', category: 'jugador' },
      { word: 'MANGO', clue: 'Apodo de un delantero histórico del Deportivo Cali', category: 'jugador' },
      { word: 'CLASICO', clue: 'Partido entre Deportivo Cali y América', category: 'clasico' },
      { word: 'VALLECAUCANO', clue: 'Adjetivo del clásico entre Cali y América', category: 'clasico' },
      { word: 'ESCUDO', clue: 'Símbolo del equipo que lleva la cruz verde', category: 'identidad' },
      { word: 'FARID', clue: 'Nombre de Mondragón, arquero que jugó en Cali', category: 'jugador' },
      { word: 'MONDRAGON', clue: 'Apellido de Farid, arquero histórico del Cali', category: 'jugador' },
      { word: 'BERMUDEZ', clue: 'Apellido de un defensa central histórico del Cali', category: 'jugador' },
      { word: 'LIZCANO', clue: 'Apellido de un goleador histórico verdiblanco', category: 'jugador' },
      { word: 'SANGRE', clue: 'Tipo de hinchada: ___ Verde', category: 'hinchada' },
      { word: 'RIVERA', clue: 'Apellido de un volante del Deportivo Cali', category: 'jugador' },
      { word: 'PENA', clue: 'Apellido de un mediocampista histórico del Cali', category: 'jugador' },
      { word: 'ROMANA', clue: 'Apellido de un jugador histórico del Cali', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un defensa del Deportivo Cali', category: 'jugador' },
      { word: 'CABRERA', clue: 'Apellido de un técnico del Deportivo Cali', category: 'tecnico' },
      { word: 'BLANCO', clue: 'Color que acompaña al verde en la bandera del Cali', category: 'identidad' },
      { word: 'CANDELARIA', clue: 'Apellido de un delantero del Deportivo Cali', category: 'jugador' },
      { word: 'LOAIZA', clue: 'Apellido de un portero del Deportivo Cali', category: 'jugador' },
      { word: 'MURILLO', clue: 'Apellido de un defensa histórico verdiblanco', category: 'jugador' },
      { word: 'ANGULO', clue: 'Apellido de un volante del Deportivo Cali', category: 'jugador' },
    ]
  },
  {
    id: 'atletico-junior',
    name: 'Junior FC',
    color: '#c8102e',
    city: 'Barranquilla',
    words: [
      { word: 'JUNIOR', clue: 'Nombre del equipo rojiblanco de Barranquilla', category: 'identidad' },
      { word: 'ROJIBLANCO', clue: 'Combinación de colores del Junior FC', category: 'identidad' },
      { word: 'BARRANQUILLA', clue: 'Ciudad donde fue fundado Junior en 1924', category: 'geografia' },
      { word: 'METROPOLITANO', clue: 'Nombre del estadio donde juega Junior: ___ Roberto Meléndez', category: 'estadio' },
      { word: 'ROBERTO', clue: 'Nombre que lleva el estadio de Junior: ___ Meléndez', category: 'estadio' },
      { word: 'TIBURON', clue: 'Apodo de Junior por su cercanía al mar', category: 'apodo' },
      { word: 'ATLANTICO', clue: 'Departamento donde está radicado Junior', category: 'geografia' },
      { word: 'CARIBE', clue: 'Región de Colombia donde está Junior', category: 'geografia' },
      { word: 'NUEVE', clue: 'Número de títulos de liga de Junior FC', category: 'historia' },
      { word: 'GARRA', clue: 'Cualidad característica del equipo tiburón', category: 'apodo' },
      { word: 'CARLOS', clue: 'Nombre de Bacca, delantero goleador de Junior', category: 'jugador' },
      { word: 'BACCA', clue: 'Apellido de Carlos, delantero ídolo del tiburón', category: 'jugador' },
      { word: 'TEOFILO', clue: 'Nombre de Gutiérrez, delantero que jugó en Junior', category: 'jugador' },
      { word: 'GUTIERREZ', clue: 'Apellido de Teófilo, goleador que pasó por Junior', category: 'jugador' },
      { word: 'MALDONADO', clue: 'Apellido de un delantero histórico de Junior', category: 'jugador' },
      { word: 'PENARANDA', clue: 'Apellido de un volante creativo de Junior', category: 'jugador' },
      { word: 'CARNIVAL', clue: 'Fiesta de Barranquilla que inspira los colores del equipo', category: 'cultura' },
      { word: 'FESTEJO', clue: 'Celebración típica de la costa que se ve en los goles de Junior', category: 'cultura' },
      { word: 'PUERTO', clue: 'Tipo de ciudad que es Barranquilla', category: 'geografia' },
      { word: 'MAGDALENA', clue: 'Río que desemboca en Barranquilla', category: 'geografia' },
      { word: 'COPA', clue: 'Torneo que Junior ha ganado en repetidas ocasiones', category: 'torneo' },
      { word: 'VASQUEZ', clue: 'Apellido de un mediocampista histórico del tiburón', category: 'jugador' },
      { word: 'PERNIA', clue: 'Apellido de un defensa histórico de Junior', category: 'jugador' },
      { word: 'HERNAN', clue: 'Nombre de Dario Gómez, técnico histórico de Junior', category: 'tecnico' },
      { word: 'DARIO', clue: 'Segundo nombre del técnico Gómez, campeón con Junior', category: 'tecnico' },
      { word: 'CRUCETA', clue: 'Apellido de un volante de Junior', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un portero de Junior', category: 'jugador' },
      { word: 'BORJA', clue: 'Apellido de un delantero goleador de Junior', category: 'jugador' },
      { word: 'SOMBRERO', clue: 'Prenda típica costeña que se ve en la hinchada', category: 'cultura' },
      { word: 'MERIENDA', clue: 'Apellido de un delantero histórico de Junior', category: 'jugador' },
    ]
  },
  {
    id: 'independiente-santa-fe',
    name: 'Santa Fe',
    color: '#c8102e',
    city: 'Bogotá',
    words: [
      { word: 'SANTAFE', clue: 'Nombre del equipo cardenal de Bogotá', category: 'identidad' },
      { word: 'CARDENAL', clue: 'Apodo de Santa Fe por su color rojo', category: 'apodo' },
      { word: 'BOGOTA', clue: 'Ciudad donde fue fundado Santa Fe en 1941', category: 'geografia' },
      { word: 'NEMESIO', clue: 'Nombre del estadio donde juega Santa Fe: Estadio ___ Camacho', category: 'estadio' },
      { word: 'CAMACHO', clue: 'Apellido que completa el nombre del estadio de Santa Fe', category: 'estadio' },
      { word: 'ROJO', clue: 'Color característico de Santa Fe', category: 'identidad' },
      { word: 'BLANCO', clue: 'Color que acompaña al rojo en la bandera de Santa Fe', category: 'identidad' },
      { word: 'CUNDINAMARCA', clue: 'Departamento donde está radicado Santa Fe', category: 'geografia' },
      { word: 'NUEVE', clue: 'Número de títulos de liga de Santa Fe', category: 'historia' },
      { word: 'ALFONSO', clue: 'Nombre de Canón, goleador histórico de Santa Fe', category: 'jugador' },
      { word: 'CANON', clue: 'Apellido de Alfonso, goleador histórico cardenal', category: 'jugador' },
      { word: 'LIBERTADORES', clue: 'Torneo continental que Santa Fe ganó en 2015 (Suruga Bank)', category: 'torneo' },
      { word: 'SURUGABANK', clue: 'Torneo intercontinental que Santa Fe ganó en 2016', category: 'torneo' },
      { word: 'WILDER', clue: 'Nombre de Guisao, delantero de Santa Fe', category: 'jugador' },
      { word: 'GUISAO', clue: 'Apellido de Wilder, delantero que jugó en Santa Fe', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un mediocampista del cardenal', category: 'jugador' },
      { word: 'CLASICO', clue: 'Partido entre Santa Fe y Millonarios', category: 'clasico' },
      { word: 'CAPITALINO', clue: 'Adjetivo del clásico bogotano', category: 'clasico' },
      { word: 'PRESIDENTE', clue: 'Cargo máximo del club cardenal', category: 'directiva' },
      { word: 'BARRA', clue: 'Grupo organizado de hinchas de Santa Fe', category: 'hinchada' },
      { word: 'GUARDIA', clue: 'Parte del nombre de la barra de Santa Fe: La ___ Roja', category: 'hinchada' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Santa Fe', category: 'jugador' },
      { word: 'MOSQUERA', clue: 'Apellido de un volante del cardenal', category: 'jugador' },
      { word: 'LEAL', clue: 'Apellido de un defensa de Santa Fe', category: 'jugador' },
      { word: 'ROMERO', clue: 'Apellido de un delantero del cardenal', category: 'jugador' },
      { word: 'ORTIZ', clue: 'Apellido de un técnico de Santa Fe', category: 'tecnico' },
      { word: 'BALANTA', clue: 'Apellido de un defensa de Santa Fe', category: 'jugador' },
      { word: 'VILLARRAGA', clue: 'Apellido de un volante cardenal', category: 'jugador' },
      { word: 'CASTELLANOS', clue: 'Apellido de un delantero de Santa Fe', category: 'jugador' },
      { word: 'CHARRUA', clue: 'Apodo de un jugador uruguayo que jugó en Santa Fe', category: 'jugador' },
    ]
  },
  {
    id: 'independiente-medellin',
    name: 'Independiente Medellín',
    color: '#e31937',
    city: 'Medellín',
    words: [
      { word: 'MEDELLIN', clue: 'Nombre del equipo rojo de Medellín', category: 'identidad' },
      { word: 'ROJO', clue: 'Color característico del Independiente Medellín', category: 'identidad' },
      { word: 'INDEPENDIENTE', clue: 'Primera parte del nombre completo del equipo', category: 'identidad' },
      { word: 'ATANASIO', clue: 'Nombre del estadio donde juega el Medellín', category: 'estadio' },
      { word: 'PODEROSO', clue: 'Apodo del Independiente Medellín', category: 'apodo' },
      { word: 'ANTIOQUIA', clue: 'Departamento donde está radicado el Medellín', category: 'geografia' },
      { word: 'SEIS', clue: 'Número de títulos de liga del Independiente Medellín', category: 'historia' },
      { word: 'DAVID', clue: 'Nombre de González, arquero histórico del Medellín', category: 'jugador' },
      { word: 'GONZALEZ', clue: 'Apellido de David, arquero del poderoso', category: 'jugador' },
      { word: 'GAVIRIA', clue: 'Apellido de un volante del Medellín', category: 'jugador' },
      { word: 'CLASICO', clue: 'Partido entre Medellín y Atlético Nacional', category: 'clasico' },
      { word: 'PAISA', clue: 'Adjetivo del clásico entre Medellín y Nacional', category: 'clasico' },
      { word: 'BRAYAN', clue: 'Nombre de un mediocampista del Medellín', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa del poderoso', category: 'jugador' },
      { word: 'HERRERA', clue: 'Apellido de un delantero del Medellín', category: 'jugador' },
      { word: 'RICAURTE', clue: 'Apellido de un volante del Medellín', category: 'jugador' },
      { word: 'COPA', clue: 'Torneo que el Medellín ha ganado', category: 'torneo' },
      { word: 'LIBERTADORES', clue: 'Torneo continental donde el Medellín ha participado', category: 'torneo' },
      { word: 'QUINTERO', clue: 'Apellido de un volante del Medellín', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un defensa del poderoso', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Medellín', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero del Medellín', category: 'jugador' },
      { word: 'TORO', clue: 'Apellido de un defensa del Medellín', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un goleador del poderoso', category: 'jugador' },
      { word: 'URIBE', clue: 'Apellido de un volante del Medellín', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un delantero del poderoso', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un defensa del Medellín', category: 'jugador' },
      { word: 'LOPERA', clue: 'Apellido de un volante del poderoso', category: 'jugador' },
      { word: 'GUERRA', clue: 'Apellido de un mediocampista del Medellín', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un técnico del Medellín', category: 'tecnico' },
    ]
  },
  {
    id: 'once-caldas',
    name: 'Once Caldas',
    color: '#0033a0',
    city: 'Manizales',
    words: [
      { word: 'ONCE', clue: 'Primera parte del nombre del equipo de Manizales', category: 'identidad' },
      { word: 'CALDAS', clue: 'Apellido del departamento donde juega este equipo', category: 'identidad' },
      { word: 'MANIZALES', clue: 'Ciudad donde fue fundado el Once Caldas', category: 'geografia' },
      { word: 'PALOGRANDE', clue: 'Nombre del estadio del Once Caldas', category: 'estadio' },
      { word: 'BLANCO', clue: 'Color característico del Once Caldas', category: 'identidad' },
      { word: 'LIBERTADORES', clue: 'Torneo continental que Once Caldas ganó en 2004', category: 'torneo' },
      { word: 'CUATRO', clue: 'Número de títulos de liga del Once Caldas', category: 'historia' },
      { word: 'MUNIRRANTE', clue: 'Apellido de un jugador histórico del Once Caldas', category: 'jugador' },
      { word: 'HENAO', clue: 'Apellido de un portero del Once Caldas', category: 'jugador' },
      { word: 'SINISTERRA', clue: 'Apellido de Luis, extremo que pasó por Once Caldas', category: 'jugador' },
      { word: 'LUIS', clue: 'Nombre de Sinisterra, extremo del Once Caldas', category: 'jugador' },
      { word: 'CORONADO', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
      { word: 'ARIZALA', clue: 'Apellido de un delantero del Once Caldas', category: 'jugador' },
      { word: 'JOHAN', clue: 'Nombre de Caballero, defensa del Once Caldas', category: 'jugador' },
      { word: 'CABALLERO', clue: 'Apellido de Johan, defensa del Once Caldas', category: 'jugador' },
      { word: 'VELASQUEZ', clue: 'Apellido de un delantero del Once Caldas', category: 'jugador' },
      { word: 'ZULETA', clue: 'Apellido de un defensa del Once Caldas', category: 'jugador' },
      { word: 'GALVIZ', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
      { word: 'PEÑA', clue: 'Apellido de un defensa del Once Caldas', category: 'jugador' },
      { word: 'RICAURTE', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
      { word: 'MONTANO', clue: 'Apellido de un jugador del Once Caldas', category: 'jugador' },
      { word: 'CAMPAÑA', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Once Caldas', category: 'tecnico' },
      { word: 'MONTOYA', clue: 'Apellido de un defensa del Once Caldas', category: 'jugador' },
      { word: 'PATINO', clue: 'Apellido de un delantero del Once Caldas', category: 'jugador' },
      { word: 'AGUIRRE', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
      { word: 'SOTO', clue: 'Apellido de un defensa del Once Caldas', category: 'jugador' },
      { word: 'RUIZ', clue: 'Apellido de un portero del Once Caldas', category: 'jugador' },
      { word: 'RAMOS', clue: 'Apellido de un defensa del Once Caldas', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un volante del Once Caldas', category: 'jugador' },
    ]
  },
  {
    id: 'deportes-tolima',
    name: 'Deportes Tolima',
    color: '#fdd835',
    city: 'Ibagué',
    words: [
      { word: 'TOLIMA', clue: 'Nombre del equipo vinotinto y dorado de Ibagué', category: 'identidad' },
      { word: 'VINOTINTO', clue: 'Color característico del Deportes Tolima', category: 'identidad' },
      { word: 'IBAGUE', clue: 'Ciudad donde fue fundado el Deportes Tolima', category: 'geografia' },
      { word: 'MANUEL', clue: 'Nombre del estadio del Tolima: ___ Murillo Toro', category: 'estadio' },
      { word: 'MURILLO', clue: 'Segundo apellido del estadio del Tolima', category: 'estadio' },
      { word: 'DORADO', clue: 'Color que acompaña al vinotinto en el Tolima', category: 'identidad' },
      { word: 'TRES', clue: 'Número de títulos de liga del Deportes Tolima', category: 'historia' },
      { word: 'ALIRO', clue: 'Nombre de un mediocampista histórico del Tolima', category: 'jugador' },
      { word: 'ANGULO', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'ROBAYO', clue: 'Apellido de un volante del Deportes Tolima', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un portero del Tolima', category: 'jugador' },
      { word: 'MENDEZ', clue: 'Apellido de un delantero del Tolima', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Tolima', category: 'tecnico' },
      { word: 'MOSQUERA', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'GRISALES', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'GUTIERREZ', clue: 'Apellido de un delantero del Tolima', category: 'jugador' },
      { word: 'ARISTIZABAL', clue: 'Apellido de un mediocampista del Tolima', category: 'jugador' },
      { word: 'RINCON', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'PERDOMO', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'SILVA', clue: 'Apellido de un delantero del Tolima', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'VALDES', clue: 'Apellido de un portero del Tolima', category: 'jugador' },
      { word: 'PATINO', clue: 'Apellido de un delantero del Tolima', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'MONTAÑEZ', clue: 'Apellido de un volante del Tolima', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un defensa del Tolima', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero del Tolima', category: 'jugador' },
    ]
  },
  {
    id: 'atletico-bucaramanga',
    name: 'Atlético Bucaramanga',
    color: '#fdd835',
    city: 'Bucaramanga',
    words: [
      { word: 'BUCARAMANGA', clue: 'Nombre del equipo amarillo de la ciudad bonita', category: 'identidad' },
      { word: 'AMARILLO', clue: 'Color característico del Bucaramanga', category: 'identidad' },
      { word: 'SANTANDER', clue: 'Departamento donde está radicado el Bucaramanga', category: 'geografia' },
      { word: 'ALFONSO', clue: 'Nombre del estadio del Bucaramanga: ___ López', category: 'estadio' },
      { word: 'LOPEZ', clue: 'Apellido que completa el nombre del estadio de Bucaramanga', category: 'estadio' },
      { word: 'LEOPARDO', clue: 'Apodo del Atlético Bucaramanga', category: 'apodo' },
      { word: 'UNO', clue: 'Número de títulos de liga del Bucaramanga', category: 'historia' },
      { word: 'SHERPA', clue: 'Apellido de un delantero del Bucaramanga', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'PEREZ', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'MENDOZA', clue: 'Apellido de un delantero del Bucaramanga', category: 'jugador' },
      { word: 'CASTILLO', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un portero del Bucaramanga', category: 'jugador' },
      { word: 'HENAO', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'GIRALDO', clue: 'Apellido de un mediocampista del Bucaramanga', category: 'jugador' },
      { word: 'COPA', clue: 'Torneo que el Bucaramanga ganó en 2024', category: 'torneo' },
      { word: 'RANGEL', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'CAMACHO', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Bucaramanga', category: 'tecnico' },
      { word: 'TORRES', clue: 'Apellido de un delantero del Bucaramanga', category: 'jugador' },
      { word: 'CARDENAS', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'RAMOS', clue: 'Apellido de un defensa del Bucaramanga', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un delantero del Bucaramanga', category: 'jugador' },
      { word: 'GUTIERREZ', clue: 'Apellido de un volante del Bucaramanga', category: 'jugador' },
      { word: 'SILVA', clue: 'Apellido de un portero del Bucaramanga', category: 'jugador' },
    ]
  },
  {
    id: 'fortaleza-ceif',
    name: 'Fortaleza CEIF',
    color: '#e31937',
    city: 'Bogotá',
    words: [
      { word: 'FORTALEZA', clue: 'Nombre del equipo de la Cantera del Pueblo', category: 'identidad' },
      { word: 'CEIF', clue: 'Sigla que acompaña al nombre Fortaleza', category: 'identidad' },
      { word: 'BOGOTA', clue: 'Ciudad donde está radicado Fortaleza CEIF', category: 'geografia' },
      { word: 'CANDELARIA', clue: 'Nombre del estadio de Fortaleza: La ___', category: 'estadio' },
      { word: 'ROJO', clue: 'Color característico de Fortaleza CEIF', category: 'identidad' },
      { word: 'CANTERA', clue: 'Lugar donde Fortaleza forma a sus jugadores jóvenes', category: 'formacion' },
      { word: 'PUEBLO', clue: 'Fortaleza es conocido como La Cantera del ___', category: 'apodo' },
      { word: 'CUNDINAMARCA', clue: 'Departamento donde está radicado Fortaleza', category: 'geografia' },
      { word: 'UNO', clue: 'Número de títulos de liga de Fortaleza', category: 'historia' },
      { word: 'RIOS', clue: 'Apellido de un jugador de Fortaleza', category: 'jugador' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de Fortaleza', category: 'tecnico' },
      { word: 'MARTINEZ', clue: 'Apellido de un delantero de Fortaleza', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero de Fortaleza', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un delantero de Fortaleza', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'CAMACHO', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'SILVA', clue: 'Apellido de un portero de Fortaleza', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de Fortaleza', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un defensa de Fortaleza', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un volante de Fortaleza', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de Fortaleza', category: 'jugador' },
    ]
  },
  {
    id: 'deportivo-pereira',
    name: 'Deportivo Pereira',
    color: '#c8102e',
    city: 'Pereira',
    words: [
      { word: 'PEREIRA', clue: 'Nombre del equipo matecaña de Risaralda', category: 'identidad' },
      { word: 'MATECAÑA', clue: 'Apodo del Deportivo Pereira', category: 'apodo' },
      { word: 'RISARALDA', clue: 'Departamento donde está radicado el Deportivo Pereira', category: 'geografia' },
      { word: 'HERNAN', clue: 'Nombre del estadio del Pereira: ___ Ramírez Villegas', category: 'estadio' },
      { word: 'RAMIREZ', clue: 'Apellido que completa el nombre del estadio de Pereira', category: 'estadio' },
      { word: 'ROJO', clue: 'Color característico del Deportivo Pereira', category: 'identidad' },
      { word: 'UNO', clue: 'Número de títulos de liga del Deportivo Pereira', category: 'historia' },
      { word: 'BRAYAN', clue: 'Nombre de un mediocampista del Pereira', category: 'jugador' },
      { word: 'ANGULO', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'QUINONEZ', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'LOAIZA', clue: 'Apellido de un portero del Pereira', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero del Pereira', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'MONTANO', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un delantero del Pereira', category: 'jugador' },
      { word: 'PENA', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'COPA', clue: 'Torneo que el Pereira ganó en 2022', category: 'torneo' },
      { word: 'LIBERTADORES', clue: 'Torneo continental donde el Pereira debutó en 2024', category: 'torneo' },
      { word: 'CASTRO', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un portero del Pereira', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Pereira', category: 'tecnico' },
      { word: 'MARTINEZ', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un delantero del Pereira', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa del Pereira', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un volante del Pereira', category: 'jugador' },
    ]
  },
  {
    id: 'deportivo-pasto',
    name: 'Deportivo Pasto',
    color: '#1a237e',
    city: 'Pasto',
    words: [
      { word: 'PASTO', clue: 'Nombre del equipo tricolor de Nariño', category: 'identidad' },
      { word: 'TRICOLOR', clue: 'Apodo del Deportivo Pasto por sus tres colores', category: 'apodo' },
      { word: 'NARIÑO', clue: 'Departamento donde está radicado el Deportivo Pasto', category: 'geografia' },
      { word: 'LIBERTAD', clue: 'Nombre del estadio del Pasto: Estadio ___', category: 'estadio' },
      { word: 'VOLCAN', clue: 'Referencia al Galeras, volcán que vigila la ciudad de Pasto', category: 'geografia' },
      { word: 'GALERAS', clue: 'Nombre del volcán que se ve desde la ciudad de Pasto', category: 'geografia' },
      { word: 'UNO', clue: 'Número de títulos de liga del Deportivo Pasto', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero del Pasto', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero del Pasto', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero del Pasto', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Pasto', category: 'tecnico' },
      { word: 'COPA', clue: 'Torneo que el Pasto ha disputado', category: 'torneo' },
      { word: 'SILVA', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un delantero del Pasto', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un portero del Pasto', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero del Pasto', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa del Pasto', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero del Pasto', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un volante del Pasto', category: 'jugador' },
    ]
  },
  {
    id: 'la-equidad',
    name: 'La Equidad',
    color: '#2e7d32',
    city: 'Bogotá',
    words: [
      { word: 'EQUIDAD', clue: 'Nombre del equipo verde asegurador de Bogotá', category: 'identidad' },
      { word: 'VERDE', clue: 'Color característico de La Equidad', category: 'identidad' },
      { word: 'BOGOTA', clue: 'Ciudad donde está radicado La Equidad', category: 'geografia' },
      { word: 'METROPOLITANO', clue: 'Estadio donde La Equidad juega como local', category: 'estadio' },
      { word: 'ASEGURADORA', clue: 'Origen del nombre del equipo (compañía de seguros)', category: 'identidad' },
      { word: 'CERO', clue: 'Número de títulos de liga de La Equidad', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un portero de La Equidad', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un delantero de La Equidad', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero de La Equidad', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de La Equidad', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero de La Equidad', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de La Equidad', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero de La Equidad', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de La Equidad', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero de La Equidad', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa de La Equidad', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante de La Equidad', category: 'jugador' },
      { word: 'QUINTERO', clue: 'Apellido de un mediocampista de La Equidad', category: 'jugador' },
    ]
  },
  {
    id: 'jaguares-de-cordoba',
    name: 'Jaguares de Córdoba',
    color: '#f57f17',
    city: 'Montería',
    words: [
      { word: 'JAGUARES', clue: 'Nombre del equipo felino de Montería', category: 'identidad' },
      { word: 'CORDOBA', clue: 'Departamento donde está radicado Jaguares', category: 'geografia' },
      { word: 'MONTERIA', clue: 'Ciudad donde juega Jaguares de Córdoba', category: 'geografia' },
      { word: 'JARAGUEY', clue: 'Nombre del estadio de Jaguares', category: 'estadio' },
      { word: 'AMARILLO', clue: 'Color característico de Jaguares', category: 'identidad' },
      { word: 'FELINO', clue: 'Tipo de animal que representa al equipo', category: 'apodo' },
      { word: 'CERO', clue: 'Número de títulos de liga de Jaguares', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero de Jaguares', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero de Jaguares', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero de Jaguares', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de Jaguares', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero de Jaguares', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de Jaguares', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero de Jaguares', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de Jaguares', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero de Jaguares', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa de Jaguares', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante de Jaguares', category: 'jugador' },
    ]
  },
  {
    id: 'cucuta-deportivo',
    name: 'Cúcuta Deportivo',
    color: '#b71c1c',
    city: 'Cúcuta',
    words: [
      { word: 'CUCUTA', clue: 'Nombre del equipo rojinegro de la frontera', category: 'identidad' },
      { word: 'ROJINEGRO', clue: 'Combinación de colores del Cúcuta Deportivo', category: 'identidad' },
      { word: 'FRONTERA', clue: 'Característica de Cúcuta por su cercanía con Venezuela', category: 'geografia' },
      { word: 'NORTE', clue: 'Departamento donde está radicado el Cúcuta: ___ de Santander', category: 'geografia' },
      { word: 'SANTANDER', clue: 'Apellido del departamento del Cúcuta Deportivo', category: 'geografia' },
      { word: 'GENERAL', clue: 'Nombre del estadio del Cúcuta: ___ Santander', category: 'estadio' },
      { word: 'MOTILON', clue: 'Apodo del Cúcuta Deportivo', category: 'apodo' },
      { word: 'UNO', clue: 'Número de títulos de liga del Cúcuta Deportivo', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero del Cúcuta', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero del Cúcuta', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero del Cúcuta', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Cúcuta', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero del Cúcuta', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero del Cúcuta', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero del Cúcuta', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero del Cúcuta', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero del Cúcuta', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante del Cúcuta', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa del Cúcuta', category: 'jugador' },
    ]
  },
  {
    id: 'internacional-de-bogota',
    name: 'Internacional de Bogotá',
    color: '#1565c0',
    city: 'Bogotá',
    words: [
      { word: 'INTERNACIONAL', clue: 'Primera parte del nombre del equipo de la capital', category: 'identidad' },
      { word: 'BOGOTA', clue: 'Ciudad donde está radicado el equipo', category: 'geografia' },
      { word: 'AZUL', clue: 'Color característico del Internacional', category: 'identidad' },
      { word: 'CANDELARIA', clue: 'Nombre del estadio donde juega el Internacional', category: 'estadio' },
      { word: 'CERO', clue: 'Número de títulos de liga del Internacional', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero del Internacional', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero del Internacional', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero del Internacional', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico del Internacional', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero del Internacional', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero del Internacional', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero del Internacional', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero del Internacional', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero del Internacional', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa del Internacional', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante del Internacional', category: 'jugador' },
      { word: 'QUINTERO', clue: 'Apellido de un mediocampista del Internacional', category: 'jugador' },
      { word: 'CUNDINAMARCA', clue: 'Departamento donde está radicado el equipo', category: 'geografia' },
    ]
  },
  {
    id: 'alianza-valledupar',
    name: 'Alianza Valledupar',
    color: '#00838f',
    city: 'Valledupar',
    words: [
      { word: 'ALIANZA', clue: 'Primera parte del nombre del equipo del Cesar', category: 'identidad' },
      { word: 'VALLEDUPAR', clue: 'Ciudad donde está radicado el equipo', category: 'geografia' },
      { word: 'CESAR', clue: 'Departamento donde está radicado Alianza', category: 'geografia' },
      { word: 'ARROYO', clue: 'Nombre del estadio de Alianza: ___ y Seco', category: 'estadio' },
      { word: 'CELESTE', clue: 'Color característico de Alianza Valledupar', category: 'identidad' },
      { word: 'CERO', clue: 'Número de títulos de liga de Alianza', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero de Alianza', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero de Alianza', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero de Alianza', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de Alianza', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero de Alianza', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de Alianza', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero de Alianza', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de Alianza', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero de Alianza', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa de Alianza', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante de Alianza', category: 'jugador' },
      { word: 'QUINTERO', clue: 'Apellido de un mediocampista de Alianza', category: 'jugador' },
    ]
  },
  {
    id: 'boyaca-chico',
    name: 'Boyacá Chicó',
    color: '#e65100',
    city: 'Tunja',
    words: [
      { word: 'CHICO', clue: 'Última parte del nombre del equipo de Tunja', category: 'identidad' },
      { word: 'BOYACA', clue: 'Departamento donde está radicado Chicó', category: 'geografia' },
      { word: 'TUNJA', clue: 'Ciudad donde juega Boyacá Chicó', category: 'geografia' },
      { word: 'LAINDEPENDENCIA', clue: 'Nombre del estadio de Chicó en Tunja', category: 'estadio' },
      { word: 'NARANJA', clue: 'Color característico de Boyacá Chicó', category: 'identidad' },
      { word: 'UNO', clue: 'Número de títulos de liga de Boyacá Chicó', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero de Chicó', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero de Chicó', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero de Chicó', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de Chicó', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero de Chicó', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de Chicó', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero de Chicó', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de Chicó', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero de Chicó', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa de Chicó', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante de Chicó', category: 'jugador' },
      { word: 'QUINTERO', clue: 'Apellido de un mediocampista de Chicó', category: 'jugador' },
    ]
  },
  {
    id: 'llaneros',
    name: 'Llaneros',
    color: '#4e342e',
    city: 'Villavicencio',
    words: [
      { word: 'LLANEROS', clue: 'Nombre del equipo de los llanos orientales', category: 'identidad' },
      { word: 'VILLAVICENCIO', clue: 'Ciudad donde juega Llaneros', category: 'geografia' },
      { word: 'META', clue: 'Departamento donde está radicado Llaneros', category: 'geografia' },
      { word: 'MANUEL', clue: 'Nombre del estadio de Llaneros: ___ Calvo Lombana', category: 'estadio' },
      { word: 'CALVO', clue: 'Apellido que completa el nombre del estadio de Llaneros', category: 'estadio' },
      { word: 'LLANO', clue: 'Región plana de Colombia donde juega Llaneros', category: 'geografia' },
      { word: 'CERO', clue: 'Número de títulos de liga de Llaneros', category: 'historia' },
      { word: 'PEREZ', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'ROJAS', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'MORENO', clue: 'Apellido de un delantero de Llaneros', category: 'jugador' },
      { word: 'CASTRO', clue: 'Apellido de un portero de Llaneros', category: 'jugador' },
      { word: 'HERNANDEZ', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'MARTINEZ', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'VALENCIA', clue: 'Apellido de un delantero de Llaneros', category: 'jugador' },
      { word: 'LOPEZ', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'GOMEZ', clue: 'Apellido de un técnico de Llaneros', category: 'tecnico' },
      { word: 'SILVA', clue: 'Apellido de un portero de Llaneros', category: 'jugador' },
      { word: 'RAMIREZ', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'TORRES', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'CARDONA', clue: 'Apellido de un delantero de Llaneros', category: 'jugador' },
      { word: 'ARIAS', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'RESTREPO', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'VELEZ', clue: 'Apellido de un portero de Llaneros', category: 'jugador' },
      { word: 'MUNOZ', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'DUQUE', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'OSPINA', clue: 'Apellido de un portero de Llaneros', category: 'jugador' },
      { word: 'CANO', clue: 'Apellido de un delantero de Llaneros', category: 'jugador' },
      { word: 'JARAMILLO', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
      { word: 'ARANGO', clue: 'Apellido de un defensa de Llaneros', category: 'jugador' },
      { word: 'VASQUEZ', clue: 'Apellido de un volante de Llaneros', category: 'jugador' },
    ]
  },
]

// ============================================
// Get team data by ID
// ============================================
export function getTeamData(teamId: string): TeamCrosswordData | undefined {
  return TEAM_CROSSWORD_DATA.find(t => t.id === teamId)
}

// ============================================
// Get all team IDs for rotation
// ============================================
export function getAllTeamIds(): string[] {
  return TEAM_CROSSWORD_DATA.map(t => t.id)
}
